{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7769e95f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Metal device set to: Apple M2\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-14 23:06:02.169072: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.\n",
      "2023-02-14 23:06:02.171215: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/3\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-14 23:06:02.479900: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz\n",
      "2023-02-14 23:06:02.732590: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.\n",
      "2023-02-14 23:06:02.812788: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n",
      "2023-02-14 23:06:02.812812: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n",
      "2023-02-14 23:06:02.820096: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n",
      "2023-02-14 23:06:02.820113: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n",
      "2023-02-14 23:06:03.015362: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n",
      "2023-02-14 23:06:03.015383: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x1599b7a50\n"
     ]
    },
    {
     "ename": "NotFoundError",
     "evalue": "Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_4' defined at (most recent call last):\n    File \"/Users/gedena/miniconda3/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/gedena/miniconda3/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 711, in start\n      self.io_loop.start()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n      handle._run()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 510, in dispatch_queue\n      await self.process_one()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 499, in process_one\n      await dispatch(*args)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 406, in dispatch_shell\n      await result\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 411, in do_execute\n      res = shell.run_cell(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 531, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2945, in run_cell\n      result = self._run_cell(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3000, in _run_cell\n      return runner(coro)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3203, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3382, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3442, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1t/sj3jytd91z53kgnkw3mqp59r0000gn/T/ipykernel_49624/4078121232.py\", line 36, in <module>\n      model.fit(x_train, y_train, epochs=3)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1027, in train_step\n      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n      self.apply_gradients(grads_and_vars)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n      return super().apply_gradients(grads_and_vars, name=name)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      iteration = self._internal_apply_gradients(grads_and_vars)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n      return tf.__internal__.distribute.interim.maybe_merge_call(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n      distribution.extended.update(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\n      return self._update_step_xla(grad, var, id(self._var_key(var)))\nNode: 'StatefulPartitionedCall_4'\ncould not find registered platform with id: 0x1599b7a50\n\t [[{{node StatefulPartitionedCall_4}}]] [Op:__inference_train_function_906]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 36\u001b[0m\n\u001b[1;32m     33\u001b[0m model\u001b[38;5;241m.\u001b[39mcompile(optimizer\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124madam\u001b[39m\u001b[38;5;124m'\u001b[39m, loss\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124msparse_categorical_crossentropy\u001b[39m\u001b[38;5;124m'\u001b[39m, metrics\u001b[38;5;241m=\u001b[39m[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124maccuracy\u001b[39m\u001b[38;5;124m'\u001b[39m])\n\u001b[1;32m     35\u001b[0m \u001b[38;5;66;03m# fit/train the model\u001b[39;00m\n\u001b[0;32m---> 36\u001b[0m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mx_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m3\u001b[39;49m\u001b[43m)\u001b[49m\n\u001b[1;32m     38\u001b[0m model\u001b[38;5;241m.\u001b[39msave(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mhandwritten.model\u001b[39m\u001b[38;5;124m'\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     67\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m     68\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m     69\u001b[0m     \u001b[38;5;66;03m# `tf.debugging.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m---> 70\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[1;32m     71\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m     72\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:52\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     50\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     51\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 52\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     53\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     54\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     55\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mNotFoundError\u001b[0m: Graph execution error:\n\nDetected at node 'StatefulPartitionedCall_4' defined at (most recent call last):\n    File \"/Users/gedena/miniconda3/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/gedena/miniconda3/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 711, in start\n      self.io_loop.start()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 215, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/base_events.py\", line 1906, in _run_once\n      handle._run()\n    File \"/Users/gedena/miniconda3/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 510, in dispatch_queue\n      await self.process_one()\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 499, in process_one\n      await dispatch(*args)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 406, in dispatch_shell\n      await result\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 729, in execute_request\n      reply_content = await reply_content\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 411, in do_execute\n      res = shell.run_cell(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 531, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 2945, in run_cell\n      result = self._run_cell(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3000, in _run_cell\n      return runner(coro)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3203, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3382, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3442, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/1t/sj3jytd91z53kgnkw3mqp59r0000gn/T/ipykernel_49624/4078121232.py\", line 36, in <module>\n      model.fit(x_train, y_train, epochs=3)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/engine/training.py\", line 1027, in train_step\n      self.optimizer.minimize(loss, self.trainable_variables, tape=tape)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 527, in minimize\n      self.apply_gradients(grads_and_vars)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1140, in apply_gradients\n      return super().apply_gradients(grads_and_vars, name=name)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 634, in apply_gradients\n      iteration = self._internal_apply_gradients(grads_and_vars)\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1166, in _internal_apply_gradients\n      return tf.__internal__.distribute.interim.maybe_merge_call(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1216, in _distributed_apply_gradients_fn\n      distribution.extended.update(\n    File \"/Users/gedena/miniconda3/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py\", line 1211, in apply_grad_to_update_var\n      return self._update_step_xla(grad, var, id(self._var_key(var)))\nNode: 'StatefulPartitionedCall_4'\ncould not find registered platform with id: 0x1599b7a50\n\t [[{{node StatefulPartitionedCall_4}}]] [Op:__inference_train_function_906]"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import cv2\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt \n",
    "import tensorflow as tf \n",
    "\n",
    "mnist = tf.keras.datasets.mnist\n",
    "\n",
    "# loading data\n",
    "(x_train, y_train), (x_test, y_test) = mnist.load_data()\n",
    "\n",
    "# scaling down, normilizing\n",
    "x_train = tf.keras.utils.normalize(x_train, axis=1)\n",
    "x_test = tf.keras.utils.normalize(x_test, axis=1)\n",
    "\n",
    "# creating model for nural networlk\n",
    "model = tf.keras.models.Sequential()\n",
    "\n",
    "\n",
    "# adding layers to nueral network\n",
    "\n",
    "# flatten layer\n",
    "model.add(tf.keras.layers.Flatten(input_shape=(28,28)))\n",
    "# dense layer\n",
    "model.add(tf.keras.layers.Dense(128, activation='relu'))\n",
    "# dense layer\n",
    "model.add(tf.keras.layers.Dense(128, activation='relu'))\n",
    "# dense layer\n",
    "model.add(tf.keras.layers.Dense(10, activation='softmax'))\n",
    "\n",
    "\n",
    "# compile the model\n",
    "model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])\n",
    "\n",
    "# fit/train the model\n",
    "model.fit(x_train, y_train, epochs=3)\n",
    "\n",
    "model.save('handwritten.model')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "265e1e44",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow-macos==2.9\n",
      "  Downloading tensorflow_macos-2.9.0-cp310-cp310-macosx_11_0_arm64.whl (200.6 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m200.6/200.6 MB\u001b[0m \u001b[31m10.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m00:01\u001b[0m00:01\u001b[0m\n",
      "\u001b[?25hCollecting tensorflow-metal==0.5.0\n",
      "  Downloading tensorflow_metal-0.5.0-cp310-cp310-macosx_11_0_arm64.whl (1.4 MB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m1.4/1.4 MB\u001b[0m \u001b[31m22.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0ma \u001b[36m0:00:01\u001b[0m\n",
      "\u001b[?25hCollecting tensorflow-gpu\n",
      "  Downloading tensorflow-gpu-2.12.0.tar.gz (2.6 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting opencv-python\n",
      "  Using cached opencv_python-4.7.0.68-cp37-abi3-macosx_11_0_arm64.whl (31.1 MB)\n",
      "Requirement already satisfied: matplotlib in /Users/gedena/miniconda3/lib/python3.10/site-packages (3.7.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (15.0.6.1)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (2.2.0)\n",
      "Requirement already satisfied: protobuf>=3.9.2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (3.19.6)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (3.3.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (3.6.0)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.14.1)\n",
      "Collecting keras<2.10.0,>=2.9.0rc0\n",
      "  Using cached keras-2.9.0-py2.py3-none-any.whl (1.6 MB)\n",
      "Collecting keras-preprocessing>=1.1.1\n",
      "  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.4.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (4.4.0)\n",
      "Requirement already satisfied: six>=1.12.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.16.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (0.4.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.42.0)\n",
      "Requirement already satisfied: packaging in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (23.0)\n",
      "Requirement already satisfied: setuptools in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (65.6.3)\n",
      "Requirement already satisfied: numpy>=1.20 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.24.2)\n",
      "Collecting flatbuffers<2,>=1.12\n",
      "  Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (1.6.3)\n",
      "Collecting tensorflow-estimator<2.10.0,>=2.9.0rc0\n",
      "  Using cached tensorflow_estimator-2.9.0-py2.py3-none-any.whl (438 kB)\n",
      "Collecting tensorboard<2.10,>=2.9\n",
      "  Using cached tensorboard-2.9.1-py3-none-any.whl (5.8 MB)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos==2.9) (0.2.0)\n",
      "Requirement already satisfied: wheel~=0.35 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-metal==0.5.0) (0.37.1)\n",
      "Collecting six>=1.12.0\n",
      "  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)\n",
      "Collecting python_version>\"3.7\"\n",
      "  Downloading python_version-0.0.2-py2.py3-none-any.whl (3.4 kB)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (1.0.7)\n",
      "Requirement already satisfied: pyparsing>=2.3.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (3.0.9)\n",
      "Requirement already satisfied: cycler>=0.10 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (0.11.0)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (2.8.2)\n",
      "Requirement already satisfied: kiwisolver>=1.0.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (1.4.4)\n",
      "Requirement already satisfied: pillow>=6.2.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (9.4.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from matplotlib) (4.38.0)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2.16.0)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2.2.3)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (3.4.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (0.6.1)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2.28.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (1.8.1)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (0.4.6)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (5.3.0)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (4.9)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (1.3.1)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (3.4)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (1.26.14)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2022.12.7)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (2.1.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.10,>=2.9->tensorflow-macos==2.9) (3.2.2)\n",
      "Building wheels for collected packages: tensorflow-gpu\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "  Building wheel for tensorflow-gpu (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1t/sj3jytd91z53kgnkw3mqp59r0000gn/T/pip-install-d8ksgdsy/tensorflow-gpu_510ba77005bd44a0962bfa5f8597c582/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for tensorflow-gpu\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for tensorflow-gpu\n",
      "Failed to build tensorflow-gpu\n",
      "Installing collected packages: python_version, keras, flatbuffers, tensorflow-gpu, tensorflow-estimator, six, opencv-python, tensorflow-metal, keras-preprocessing, tensorboard, tensorflow-macos\n",
      "  Attempting uninstall: keras\n",
      "    Found existing installation: keras 2.11.0\n",
      "    Uninstalling keras-2.11.0:\n",
      "      Successfully uninstalled keras-2.11.0\n",
      "  Attempting uninstall: flatbuffers\n",
      "    Found existing installation: flatbuffers 23.1.21\n",
      "    Uninstalling flatbuffers-23.1.21:\n",
      "      Successfully uninstalled flatbuffers-23.1.21\n",
      "  Running setup.py install for tensorflow-gpu ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mRunning setup.py install for tensorflow-gpu\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[18 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1t/sj3jytd91z53kgnkw3mqp59r0000gn/T/pip-install-d8ksgdsy/tensorflow-gpu_510ba77005bd44a0962bfa5f8597c582/setup.py\", line 37, in <module>\n",
      "  \u001b[31m   \u001b[0m     raise Exception(TF_REMOVAL_WARNING)\n",
      "  \u001b[31m   \u001b[0m Exception:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m The \"tensorflow-gpu\" package has been removed!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Please install \"tensorflow\" instead.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Other than the name, the two packages have been identical\n",
      "  \u001b[31m   \u001b[0m since TensorFlow 2.1, or roughly since Sep 2019. For more\n",
      "  \u001b[31m   \u001b[0m information, see: pypi.org/project/tensorflow-gpu\n",
      "  \u001b[31m   \u001b[0m =========================================================\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1mlegacy-install-failure\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while trying to install package.\n",
      "\u001b[31m╰─>\u001b[0m tensorflow-gpu\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for output from the failure.\n",
      "\u001b[?25h"
     ]
    }
   ],
   "source": [
    "!pip install tensorflow-macos==2.9 tensorflow-metal==0.5.0 tensorflow-gpu opencv-python matplotlib\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "161f093e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package                 Version\r\n",
      "----------------------- -----------\r\n",
      "absl-py                 1.4.0\r\n",
      "anaconda-clean          1.0\r\n",
      "anyio                   3.5.0\r\n",
      "appnope                 0.1.2\r\n",
      "argon2-cffi             21.3.0\r\n",
      "argon2-cffi-bindings    21.2.0\r\n",
      "asttokens               2.0.5\r\n",
      "astunparse              1.6.3\r\n",
      "attrs                   22.1.0\r\n",
      "Babel                   2.11.0\r\n",
      "backcall                0.2.0\r\n",
      "beautifulsoup4          4.11.1\r\n",
      "bleach                  4.1.0\r\n",
      "brotlipy                0.7.0\r\n",
      "cachetools              5.3.0\r\n",
      "certifi                 2022.12.7\r\n",
      "cffi                    1.15.1\r\n",
      "charset-normalizer      2.0.4\r\n",
      "comm                    0.1.2\r\n",
      "conda                   23.1.0\r\n",
      "conda-content-trust     0.1.3\r\n",
      "conda-package-handling  2.0.2\r\n",
      "conda_package_streaming 0.7.0\r\n",
      "contourpy               1.0.7\r\n",
      "cryptography            38.0.4\r\n",
      "cycler                  0.11.0\r\n",
      "debugpy                 1.5.1\r\n",
      "decorator               5.1.1\r\n",
      "defusedxml              0.7.1\r\n",
      "entrypoints             0.4\r\n",
      "executing               0.8.3\r\n",
      "fastjsonschema          2.16.2\r\n",
      "flatbuffers             1.12\r\n",
      "flit_core               3.6.0\r\n",
      "fonttools               4.38.0\r\n",
      "gast                    0.4.0\r\n",
      "google-auth             2.16.0\r\n",
      "google-auth-oauthlib    0.4.6\r\n",
      "google-pasta            0.2.0\r\n",
      "grpcio                  1.42.0\r\n",
      "h5py                    3.6.0\r\n",
      "idna                    3.4\r\n",
      "ipykernel               6.19.2\r\n",
      "ipython                 8.9.0\r\n",
      "ipython-genutils        0.2.0\r\n",
      "ipywidgets              7.6.5\r\n",
      "jedi                    0.18.1\r\n",
      "Jinja2                  3.1.2\r\n",
      "joblib                  1.2.0\r\n",
      "json5                   0.9.6\r\n",
      "jsonschema              4.16.0\r\n",
      "jupyter                 1.0.0\r\n",
      "jupyter_client          7.4.9\r\n",
      "jupyter-console         6.4.4\r\n",
      "jupyter_core            5.1.1\r\n",
      "jupyter-server          1.23.4\r\n",
      "jupyterlab              3.5.3\r\n",
      "jupyterlab-pygments     0.1.2\r\n",
      "jupyterlab_server       2.16.5\r\n",
      "jupyterlab-widgets      1.0.0\r\n",
      "keras                   2.9.0\r\n",
      "kiwisolver              1.4.4\r\n",
      "libclang                15.0.6.1\r\n",
      "lxml                    4.9.1\r\n",
      "Markdown                3.4.1\r\n",
      "MarkupSafe              2.1.2\r\n",
      "matplotlib              3.7.0\r\n",
      "matplotlib-inline       0.1.6\r\n",
      "mistune                 0.8.4\r\n",
      "nbclassic               0.4.8\r\n",
      "nbclient                0.5.13\r\n",
      "nbconvert               6.5.4\r\n",
      "nbformat                5.7.0\r\n",
      "nest-asyncio            1.5.6\r\n",
      "notebook                6.5.2\r\n",
      "notebook_shim           0.2.2\r\n",
      "numpy                   1.24.2\r\n",
      "oauthlib                3.2.2\r\n",
      "opt-einsum              3.3.0\r\n",
      "packaging               23.0\r\n",
      "pandas                  1.5.3\r\n",
      "pandocfilters           1.5.0\r\n",
      "parso                   0.8.3\r\n",
      "pexpect                 4.8.0\r\n",
      "pickleshare             0.7.5\r\n",
      "Pillow                  9.4.0\r\n",
      "pip                     22.3.1\r\n",
      "platformdirs            2.5.2\r\n",
      "plotly                  5.13.0\r\n",
      "pluggy                  1.0.0\r\n",
      "ply                     3.11\r\n",
      "prometheus-client       0.14.1\r\n",
      "prompt-toolkit          3.0.36\r\n",
      "protobuf                3.19.6\r\n",
      "psutil                  5.9.0\r\n",
      "ptyprocess              0.7.0\r\n",
      "pure-eval               0.2.2\r\n",
      "pyasn1                  0.4.8\r\n",
      "pyasn1-modules          0.2.8\r\n",
      "pycosat                 0.6.4\r\n",
      "pycparser               2.21\r\n",
      "Pygments                2.11.2\r\n",
      "pyOpenSSL               22.0.0\r\n",
      "pyparsing               3.0.9\r\n",
      "PyQt5-sip               12.11.0\r\n",
      "pyrsistent              0.18.0\r\n",
      "PySocks                 1.7.1\r\n",
      "python-dateutil         2.8.2\r\n",
      "python-version          0.0.2\r\n",
      "pytz                    2022.7.1\r\n",
      "pyzmq                   23.2.0\r\n",
      "qtconsole               5.4.0\r\n",
      "QtPy                    2.2.0\r\n",
      "requests                2.28.1\r\n",
      "requests-oauthlib       1.3.1\r\n",
      "rsa                     4.9\r\n",
      "ruamel.yaml             0.17.21\r\n",
      "ruamel.yaml.clib        0.2.6\r\n",
      "scikit-learn            1.2.1\r\n",
      "scipy                   1.10.0\r\n",
      "Send2Trash              1.8.0\r\n",
      "setuptools              65.6.3\r\n",
      "sip                     6.6.2\r\n",
      "six                     1.16.0\r\n",
      "sniffio                 1.2.0\r\n",
      "soupsieve               2.3.2.post1\r\n",
      "stack-data              0.2.0\r\n",
      "tenacity                8.2.1\r\n",
      "tensorboard             2.11.2\r\n",
      "tensorboard-data-server 0.6.1\r\n",
      "tensorboard-plugin-wit  1.8.1\r\n",
      "tensorflow-estimator    2.11.0\r\n",
      "tensorflow-metal        0.7.1\r\n",
      "termcolor               2.2.0\r\n",
      "terminado               0.17.1\r\n",
      "threadpoolctl           3.1.0\r\n",
      "tinycss2                1.2.1\r\n",
      "toml                    0.10.2\r\n",
      "tomli                   2.0.1\r\n",
      "toolz                   0.12.0\r\n",
      "tornado                 6.2\r\n",
      "tqdm                    4.64.1\r\n",
      "traitlets               5.7.1\r\n",
      "typing_extensions       4.4.0\r\n",
      "urllib3                 1.26.14\r\n",
      "wcwidth                 0.2.5\r\n",
      "webencodings            0.5.1\r\n",
      "websocket-client        0.58.0\r\n",
      "Werkzeug                2.2.3\r\n",
      "wheel                   0.37.1\r\n",
      "widgetsnbextension      3.5.2\r\n",
      "wrapt                   1.14.1\r\n",
      "zstandard               0.18.0\r\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "d4f38928",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting tensorflow-macos\n",
      "  Using cached tensorflow_macos-2.11.0-cp310-cp310-macosx_12_0_arm64.whl (215.6 MB)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.6.3)\n",
      "Collecting keras<2.12,>=2.11.0\n",
      "  Using cached keras-2.11.0-py2.py3-none-any.whl (1.7 MB)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (3.6.0)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.42.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.4.0)\n",
      "Requirement already satisfied: six>=1.12.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.16.0)\n",
      "Requirement already satisfied: numpy>=1.20 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.24.2)\n",
      "Requirement already satisfied: tensorboard<2.12,>=2.11 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (2.11.2)\n",
      "Requirement already satisfied: setuptools in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (65.6.3)\n",
      "Requirement already satisfied: packaging in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (23.0)\n",
      "Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (2.11.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (0.4.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (15.0.6.1)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (1.14.1)\n",
      "Requirement already satisfied: protobuf<3.20,>=3.9.2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (3.19.6)\n",
      "Collecting flatbuffers>=2.0\n",
      "  Using cached flatbuffers-23.1.21-py2.py3-none-any.whl (26 kB)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (4.4.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (0.2.0)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (3.3.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorflow-macos) (2.2.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow-macos) (0.37.1)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (0.6.1)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (3.4.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (2.16.0)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (2.28.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (1.8.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (2.2.3)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow-macos) (0.4.6)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-macos) (5.3.0)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-macos) (4.9)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-macos) (0.2.8)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-macos) (1.3.1)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-macos) (2022.12.7)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-macos) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-macos) (3.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow-macos) (1.26.14)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow-macos) (2.1.2)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow-macos) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/gedena/miniconda3/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow-macos) (3.2.2)\n",
      "Installing collected packages: flatbuffers, keras, tensorflow-macos\n",
      "  Attempting uninstall: flatbuffers\n",
      "    Found existing installation: flatbuffers 1.12\n",
      "    Uninstalling flatbuffers-1.12:\n",
      "      Successfully uninstalled flatbuffers-1.12\n",
      "  Attempting uninstall: keras\n",
      "    Found existing installation: keras 2.9.0\n",
      "    Uninstalling keras-2.9.0:\n",
      "      Successfully uninstalled keras-2.9.0\n",
      "Successfully installed flatbuffers-23.1.21 keras-2.11.0 tensorflow-macos-2.11.0\n"
     ]
    }
   ],
   "source": [
    "!pip install tensorflow-macos"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "e97ba53a",
   "metadata": {},
   "outputs": [
    {
     "ename": "SyntaxError",
     "evalue": "invalid syntax (16620906.py, line 1)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;36m  Cell \u001b[0;32mIn[5], line 1\u001b[0;36m\u001b[0m\n\u001b[0;31m    tensorflow list!\u001b[0m\n\u001b[0m               ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m invalid syntax\n"
     ]
    }
   ],
   "source": [
    "tensorflow list!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "f2883a24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Package                 Version\r\n",
      "----------------------- -----------\r\n",
      "absl-py                 1.4.0\r\n",
      "anaconda-clean          1.0\r\n",
      "anyio                   3.5.0\r\n",
      "appnope                 0.1.2\r\n",
      "argon2-cffi             21.3.0\r\n",
      "argon2-cffi-bindings    21.2.0\r\n",
      "asttokens               2.0.5\r\n",
      "astunparse              1.6.3\r\n",
      "attrs                   22.1.0\r\n",
      "Babel                   2.11.0\r\n",
      "backcall                0.2.0\r\n",
      "beautifulsoup4          4.11.1\r\n",
      "bleach                  4.1.0\r\n",
      "brotlipy                0.7.0\r\n",
      "cachetools              5.3.0\r\n",
      "certifi                 2022.12.7\r\n",
      "cffi                    1.15.1\r\n",
      "charset-normalizer      2.0.4\r\n",
      "comm                    0.1.2\r\n",
      "conda                   23.1.0\r\n",
      "conda-content-trust     0.1.3\r\n",
      "conda-package-handling  2.0.2\r\n",
      "conda_package_streaming 0.7.0\r\n",
      "contourpy               1.0.7\r\n",
      "cryptography            38.0.4\r\n",
      "cycler                  0.11.0\r\n",
      "debugpy                 1.5.1\r\n",
      "decorator               5.1.1\r\n",
      "defusedxml              0.7.1\r\n",
      "entrypoints             0.4\r\n",
      "executing               0.8.3\r\n",
      "fastjsonschema          2.16.2\r\n",
      "flatbuffers             23.1.21\r\n",
      "flit_core               3.6.0\r\n",
      "fonttools               4.38.0\r\n",
      "gast                    0.4.0\r\n",
      "google-auth             2.16.0\r\n",
      "google-auth-oauthlib    0.4.6\r\n",
      "google-pasta            0.2.0\r\n",
      "grpcio                  1.42.0\r\n",
      "h5py                    3.6.0\r\n",
      "idna                    3.4\r\n",
      "ipykernel               6.19.2\r\n",
      "ipython                 8.9.0\r\n",
      "ipython-genutils        0.2.0\r\n",
      "ipywidgets              7.6.5\r\n",
      "jedi                    0.18.1\r\n",
      "Jinja2                  3.1.2\r\n",
      "joblib                  1.2.0\r\n",
      "json5                   0.9.6\r\n",
      "jsonschema              4.16.0\r\n",
      "jupyter                 1.0.0\r\n",
      "jupyter_client          7.4.9\r\n",
      "jupyter-console         6.4.4\r\n",
      "jupyter_core            5.1.1\r\n",
      "jupyter-server          1.23.4\r\n",
      "jupyterlab              3.5.3\r\n",
      "jupyterlab-pygments     0.1.2\r\n",
      "jupyterlab_server       2.16.5\r\n",
      "jupyterlab-widgets      1.0.0\r\n",
      "keras                   2.11.0\r\n",
      "kiwisolver              1.4.4\r\n",
      "libclang                15.0.6.1\r\n",
      "lxml                    4.9.1\r\n",
      "Markdown                3.4.1\r\n",
      "MarkupSafe              2.1.2\r\n",
      "matplotlib              3.7.0\r\n",
      "matplotlib-inline       0.1.6\r\n",
      "mistune                 0.8.4\r\n",
      "nbclassic               0.4.8\r\n",
      "nbclient                0.5.13\r\n",
      "nbconvert               6.5.4\r\n",
      "nbformat                5.7.0\r\n",
      "nest-asyncio            1.5.6\r\n",
      "notebook                6.5.2\r\n",
      "notebook_shim           0.2.2\r\n",
      "numpy                   1.24.2\r\n",
      "oauthlib                3.2.2\r\n",
      "opt-einsum              3.3.0\r\n",
      "packaging               23.0\r\n",
      "pandas                  1.5.3\r\n",
      "pandocfilters           1.5.0\r\n",
      "parso                   0.8.3\r\n",
      "pexpect                 4.8.0\r\n",
      "pickleshare             0.7.5\r\n",
      "Pillow                  9.4.0\r\n",
      "pip                     22.3.1\r\n",
      "platformdirs            2.5.2\r\n",
      "plotly                  5.13.0\r\n",
      "pluggy                  1.0.0\r\n",
      "ply                     3.11\r\n",
      "prometheus-client       0.14.1\r\n",
      "prompt-toolkit          3.0.36\r\n",
      "protobuf                3.19.6\r\n",
      "psutil                  5.9.0\r\n",
      "ptyprocess              0.7.0\r\n",
      "pure-eval               0.2.2\r\n",
      "pyasn1                  0.4.8\r\n",
      "pyasn1-modules          0.2.8\r\n",
      "pycosat                 0.6.4\r\n",
      "pycparser               2.21\r\n",
      "Pygments                2.11.2\r\n",
      "pyOpenSSL               22.0.0\r\n",
      "pyparsing               3.0.9\r\n",
      "PyQt5-sip               12.11.0\r\n",
      "pyrsistent              0.18.0\r\n",
      "PySocks                 1.7.1\r\n",
      "python-dateutil         2.8.2\r\n",
      "python-version          0.0.2\r\n",
      "pytz                    2022.7.1\r\n",
      "pyzmq                   23.2.0\r\n",
      "qtconsole               5.4.0\r\n",
      "QtPy                    2.2.0\r\n",
      "requests                2.28.1\r\n",
      "requests-oauthlib       1.3.1\r\n",
      "rsa                     4.9\r\n",
      "ruamel.yaml             0.17.21\r\n",
      "ruamel.yaml.clib        0.2.6\r\n",
      "scikit-learn            1.2.1\r\n",
      "scipy                   1.10.0\r\n",
      "Send2Trash              1.8.0\r\n",
      "setuptools              65.6.3\r\n",
      "sip                     6.6.2\r\n",
      "six                     1.16.0\r\n",
      "sniffio                 1.2.0\r\n",
      "soupsieve               2.3.2.post1\r\n",
      "stack-data              0.2.0\r\n",
      "tenacity                8.2.1\r\n",
      "tensorboard             2.11.2\r\n",
      "tensorboard-data-server 0.6.1\r\n",
      "tensorboard-plugin-wit  1.8.1\r\n",
      "tensorflow-estimator    2.11.0\r\n",
      "tensorflow-macos        2.11.0\r\n",
      "tensorflow-metal        0.7.1\r\n",
      "termcolor               2.2.0\r\n",
      "terminado               0.17.1\r\n",
      "threadpoolctl           3.1.0\r\n",
      "tinycss2                1.2.1\r\n",
      "toml                    0.10.2\r\n",
      "tomli                   2.0.1\r\n",
      "toolz                   0.12.0\r\n",
      "tornado                 6.2\r\n",
      "tqdm                    4.64.1\r\n",
      "traitlets               5.7.1\r\n",
      "typing_extensions       4.4.0\r\n",
      "urllib3                 1.26.14\r\n",
      "wcwidth                 0.2.5\r\n",
      "webencodings            0.5.1\r\n",
      "websocket-client        0.58.0\r\n",
      "Werkzeug                2.2.3\r\n",
      "wheel                   0.37.1\r\n",
      "widgetsnbextension      3.5.2\r\n",
      "wrapt                   1.14.1\r\n",
      "zstandard               0.18.0\r\n"
     ]
    }
   ],
   "source": [
    "!pip list"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "c22bd545",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]\n",
      "Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Metal device set to: Apple M2\n",
      "Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op RandomStandardNormal in device /job:localhost/replica:0/task:0/device:GPU:0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-14 15:34:23.873980: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.\n",
      "2023-02-14 15:34:23.874024: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)\n",
      "2023-02-14 15:34:23.882212: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:CPU:0\n",
      "2023-02-14 15:34:23.882229: I tensorflow/core/common_runtime/placer.cc:114] _EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.882232: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.885920: I tensorflow/core/common_runtime/placer.cc:114] input: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.885926: I tensorflow/core/common_runtime/placer.cc:114] _EagerConst: (_EagerConst): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.885929: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.889153: I tensorflow/core/common_runtime/placer.cc:114] shape: (_DeviceArg): /job:localhost/replica:0/task:0/device:CPU:0\n",
      "2023-02-14 15:34:23.889158: I tensorflow/core/common_runtime/placer.cc:114] RandomStandardNormal: (RandomStandardNormal): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:23.889161: I tensorflow/core/common_runtime/placer.cc:114] output_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op _EagerConst in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op RandomStandardNormal in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op AddV2 in device /job:localhost/replica:0/task:0/device:GPU:0\n",
      "Executing op Mul in device /job:localhost/replica:0/task:0/device:GPU:0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-02-14 15:34:24.244802: I tensorflow/core/common_runtime/placer.cc:114] x: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.244811: I tensorflow/core/common_runtime/placer.cc:114] y: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.244814: I tensorflow/core/common_runtime/placer.cc:114] Mul: (Mul): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.244816: I tensorflow/core/common_runtime/placer.cc:114] z_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.250484: I tensorflow/core/common_runtime/placer.cc:114] x: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.250490: I tensorflow/core/common_runtime/placer.cc:114] y: (_Arg): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.250493: I tensorflow/core/common_runtime/placer.cc:114] AddV2: (AddV2): /job:localhost/replica:0/task:0/device:GPU:0\n",
      "2023-02-14 15:34:24.250495: I tensorflow/core/common_runtime/placer.cc:114] z_RetVal: (_Retval): /job:localhost/replica:0/task:0/device:GPU:0\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "devices = tf.config.list_physical_devices()\n",
    "print(devices)\n",
    "tf.debugging.set_log_device_placement(True)\n",
    "a=tf.random.normal([100,100])\n",
    "b=tf.random.normal([100,100])\n",
    "c = a*b"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "a4f17740",
   "metadata": {},
   "outputs": [],
   "source": [
    "import os"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "68377fee",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'data/happy'"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "os.path.join('data','happy')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "7ac18ccb",
   "metadata": {},
   "outputs": [],
   "source": [
    "gpus = tf.config.experimental.list_physical_devices('GPU')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "3af6a79f",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "gpus"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "c4bf21c7",
   "metadata": {},
   "outputs": [
    {
     "ename": "RuntimeError",
     "evalue": "Physical devices cannot be modified after being initialized",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[18], line 3\u001b[0m\n\u001b[1;32m      1\u001b[0m gpus \u001b[38;5;241m=\u001b[39m tf\u001b[38;5;241m.\u001b[39mconfig\u001b[38;5;241m.\u001b[39mexperimental\u001b[38;5;241m.\u001b[39mlist_physical_devices(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mGPU\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m gpu \u001b[38;5;129;01min\u001b[39;00m gpus:\n\u001b[0;32m----> 3\u001b[0m     \u001b[43mtf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mconfig\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mexperimental\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mset_memory_growth\u001b[49m\u001b[43m(\u001b[49m\u001b[43mgpu\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/tensorflow/python/framework/config.py:716\u001b[0m, in \u001b[0;36mset_memory_growth\u001b[0;34m(device, enable)\u001b[0m\n\u001b[1;32m    691\u001b[0m \u001b[38;5;129m@tf_export\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mconfig.experimental.set_memory_growth\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m    692\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mset_memory_growth\u001b[39m(device, enable):\n\u001b[1;32m    693\u001b[0m   \u001b[38;5;124;03m\"\"\"Set if memory growth should be enabled for a `PhysicalDevice`.\u001b[39;00m\n\u001b[1;32m    694\u001b[0m \n\u001b[1;32m    695\u001b[0m \u001b[38;5;124;03m  If memory growth is enabled for a `PhysicalDevice`, the runtime initialization\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    714\u001b[0m \u001b[38;5;124;03m    RuntimeError: Runtime is already initialized.\u001b[39;00m\n\u001b[1;32m    715\u001b[0m \u001b[38;5;124;03m  \"\"\"\u001b[39;00m\n\u001b[0;32m--> 716\u001b[0m   \u001b[43mcontext\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcontext\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mset_memory_growth\u001b[49m\u001b[43m(\u001b[49m\u001b[43mdevice\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43menable\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/lib/python3.10/site-packages/tensorflow/python/eager/context.py:1643\u001b[0m, in \u001b[0;36mContext.set_memory_growth\u001b[0;34m(self, dev, enable)\u001b[0m\n\u001b[1;32m   1640\u001b[0m   \u001b[38;5;28;01mreturn\u001b[39;00m\n\u001b[1;32m   1642\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_context_handle \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[0;32m-> 1643\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\n\u001b[1;32m   1644\u001b[0m       \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mPhysical devices cannot be modified after being initialized\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m   1646\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_memory_growth_map[dev] \u001b[38;5;241m=\u001b[39m enable\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Physical devices cannot be modified after being initialized"
     ]
    }
   ],
   "source": [
    "gpus = tf.config.experimental.list_physical_devices('GPU')\n",
    "for gpu in gpus:\n",
    "    tf.config.experimental.set_memory_growth(gpu, True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1de0f48b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10 (tensorflow)",
   "language": "python",
   "name": "tensorflow"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
